### ISSUE TITLE
Milestone 2 feedback: 

### ISSUE THREAD

**Issue by Abu-Hijleh** [data301-2020-winter2/course-project-group_1051#4]
Must fix: 

- [ ] your task 5 should be a .ipynb file that includes the code, so we can run it. it is currently a .md with screenshots
- [ ] add graph titles and units to the x and y axis
- [ ] use relative addressing instead of absolute addressing (for example do not use "/Users/yiraozhang/Desktop/course-project-group_1051/data/raw/AB_NYC_2019.csv") 
- [ ] no EDA, please go back and do task 4
